# Generated by Django 5.1.7 on 2025-03-28 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentioned_users',
            field=models.ManyToManyField(related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
