# Generated by Django 5.2 on 2025-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Members Only'), ('moderators', 'Moderators Only')], default='public', max_length=10),
        ),
    ]
