# Generated by Django 5.2 on 2025-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communities_colour'),
        ('posts', '0004_post_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(related_name='posts', to='communities.topic'),
        ),
    ]
