# Generated by Django 5.2 on 2025-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communities_colour'),
        ('posts', '0005_post_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='communities.topic'),
        ),
    ]
