# Generated by Django 5.1.6 on 2025-02-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_communitymember_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communities',
            name='community_id',
        ),
        migrations.AddField(
            model_name='communities',
            name='id',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communities',
            name='pkid',
            field=models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
