# Generated by Django 5.2 on 2025-04-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_options_event_details_event_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='event_materials/'),
        ),
        migrations.AddField(
            model_name='event',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
