# Generated by Django 5.2 on 2025-05-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_materials_event_members_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='materials',
        ),
    ]
