# Generated by Django 5.1.7 on 2025-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('member', 'Member'), ('moderator', 'Moderator')], default='subscriber', max_length=20),
        ),
    ]
