# Generated by Django 5.1.7 on 2025-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('member', 'Member'), ('moderator', 'Moderator')], default='subscriber', max_length=20),
        ),
    ]
