# Generated by Django 5.1.7 on 2025-03-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_communitymember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
