# Generated by Django 5.1.7 on 2025-04-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communities_status_alter_communitymember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('club', 'Club'), ('sports', 'Sports'), ('hobby', 'Hobby'), ('support', 'Support'), ('professional', 'Professional'), ('cultural', 'Cultural'), ('religious', 'Religious'), ('political', 'Political'), ('gaming', 'Gaming'), ('technology', 'Technology'), ('arts', 'Arts'), ('music', 'Music'), ('food', 'Food'), ('health', 'Health'), ('fitness', 'Fitness'), ('travel', 'Travel'), ('environment', 'Environment'), ('science', 'Science'), ('literature', 'Literature'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
