# Generated by Django 5.2 on 2025-04-23 15:37

import communities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_communities_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communities',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communities',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('academic', 'Academic'), ('hobby', 'Hobby'), ('society', 'Society')], default='society', max_length=20),
        ),
        migrations.AlterField(
            model_name='communities',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='communities',
            name='id',
            field=models.CharField(default=communities.models.generate_nanoid, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='communities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
