# Generated by Django 5.2 on 2025-05-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_communities_options_topic_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communities',
            name='banner_url',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='communities',
            name='icon_url',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
