# Generated by Django 5.2 on 2025-05-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_communitymember_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='colour',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
