name: "UWEHub"
email_domain: live.uwe.ac.uk

users:
  init_with:
    - username: admin
      password: password
      email: uni-hub-admin@live.uwe.ac.uk
      first_name: Admin
      last_name: Account
      is_superuser: yes
      is_staff: yes
      student_id: 0000000
      profile_picture: ""

communities:
  init_with:
    - id: uwe
      name: UWE
      owner_username: admin
      auto_populate_with_test_data: yes

    - id: comp-sci
      name: Computer Science
      owner_username: admin
      auto_populate_with_test_data: yes

topics:
  init_with:
    # Academic Topics
    - name: "Programming"
      description: "Software development and coding topics"
    - name: "WebDev" 
      description: "Web development and design"
    - name: "DataScience"
      description: "Data analysis, machine learning, and statistics"
    - name: "AI"
      description: "Artificial intelligence and machine learning"
    - name: "CompSci"
      description: "Computer Science topics"
    
    # University Topics
    - name: "UWE"
      description: "University of the West of England related topics"
    - name: "StudentLife"
      description: "Student life experiences and discussions"
    - name: "CampusEvents"
      description: "Events happening on campus"
    - name: "Library"
      description: "Library resources and study spaces"
    - name: "Accommodation"
      description: "Student housing and accommodation issues"
    
    # General Topics
    - name: "Gaming"
      description: "Video games and esports"
    - name: "Music"
      description: "Music creation, appreciation, and events"
    - name: "Sports"
      description: "Athletic activities and sports news"
    - name: "Food"
      description: "Cooking, recipes, and culinary experiences"
    - name: "Travel"
      description: "Travel experiences and destinations"
    - name: "Movies"
      description: "Film and cinema discussion"
    - name: "Technology"
      description: "Tech news, gadgets, and innovations"
    - name: "Health"
      description: "Health and wellness topics"
    - name: "Fitness"
      description: "Exercise, workouts, and physical fitness"

interests:
  init_with:
    - name: "Artificial Intelligence"
      description: "Machine learning, neural networks, and AI applications"
    - name: "Athletics"
      description: "Track and field activities"
    - name: "Basketball"
      description: "Basketball and related activities"
    - name: "Blockchain"
      description: "Cryptocurrency and distributed ledger technology"
    - name: "Cultural Exchange"
      description: "Learning about different cultures"
    - name: "Cybersecurity"
      description: "Computer and network security"
    - name: "Cycling"
      description: "Road and mountain biking"
    - name: "Dance"
      description: "Various dance styles and choreography"
    - name: "Data Science"
      description: "Working with data and statistics"
    - name: "Debate"
      description: "Formal discussion and debate competitions"
    - name: "Drawing"
      description: "Sketching, illustration, and drawing"
    - name: "Entrepreneurship"
      description: "Business startups and innovation"
    - name: "Environmental Activism"
      description: "Conservation and ecological advocacy"
    - name: "Film & Video"
      description: "Filmmaking and video production"
    - name: "Fitness"
      description: "Working out and physical fitness"
    - name: "Football"
      description: "Association football/soccer"
    - name: "Gaming"
      description: "Video games and game development"
    - name: "Martial Arts"
      description: "Various martial arts disciplines"
    - name: "Mobile Development"
      description: "Creating mobile applications"
    - name: "Music"
      description: "Playing instruments, singing, or producing music"
    - name: "Painting"
      description: "Creating art through painting"
    - name: "Photography"
      description: "Taking and editing photos"
    - name: "Robotics"
      description: "Building and programming robots"
    - name: "Rugby"
      description: "Rugby union and league"
    - name: "Software Development"
      description: "Programming and software engineering"
    - name: "Swimming"
      description: "Swimming and water sports"
    - name: "Tennis"
      description: "Tennis and racket sports"
    - name: "Theater"
      description: "Acting, directing, and theater production"
    - name: "Volleyball"
      description: "Volleyball and related activities"
    - name: "Volunteering"
      description: "Community service and helping others"
    - name: "Web Development"
      description: "Creating websites and web applications"
    - name: "Writing"
      description: "Creative writing, poetry, and storytelling"

courses:
  init_with:
    - course_name: "Accounting"
      department: "Business"
      description: "Recording and analyzing financial transactions"
    - course_name: "Aerospace Engineering"
      department: "Engineering"
      description: "Design of aircraft, spacecraft, and related systems"
    - course_name: "Biology"
      department: "Science"
      description: "Study of living organisms and their interactions"
    - course_name: "Biomedical Engineering"
      department: "Engineering"
      description: "Application of engineering principles to medicine and biology"
    - course_name: "Business Administration"
      department: "Business"
      description: "Management of business operations and organizations"
    - course_name: "Chemistry"
      department: "Science"
      description: "Study of substances, their properties, and reactions"
    - course_name: "Civil Engineering"
      department: "Engineering"
      description: "Design and construction of physical infrastructure"
    - course_name: "Computer Science"
      department: "Engineering"
      description: "Study of computational systems and programming"
    - course_name: "Economics"
      department: "Business"
      description: "Study of production, distribution, and consumption"
    - course_name: "Electrical Engineering"
      department: "Engineering"
      description: "Study of electricity, electronics, and electromagnetism"
    - course_name: "English Literature"
      department: "Arts"
      description: "Study of literature written in the English language"
    - course_name: "Environmental Science"
      department: "Science"
      description: "Study of environment and solutions to environmental problems"
    - course_name: "Finance"
      department: "Business"
      description: "Management of money and assets"
    - course_name: "Fine Arts"
      department: "Arts"
      description: "Visual arts, music, dance, and theater"
    - course_name: "History"
      department: "Arts"
      description: "Study of past events and human societies"
    - course_name: "International Business"
      department: "Business"
      description: "Business operations in international markets"
    - course_name: "Languages"
      department: "Arts"
      description: "Study of foreign languages and linguistics"
    - course_name: "Marketing"
      department: "Business"
      description: "Promotion and selling of products or services"
    - course_name: "Mathematics"
      department: "Science"
      description: "Study of numbers, shapes, patterns, and change"
    - course_name: "Mechanical Engineering"
      department: "Engineering"
      description: "Design and analysis of mechanical systems"
    - course_name: "Medicine"
      department: "Health"
      description: "Study of diagnosing, treating, and preventing illness"
    - course_name: "Nursing"
      department: "Health"
      description: "Healthcare and patient care"
    - course_name: "Pharmacy"
      department: "Health"
      description: "Preparation and dispensing of medicinal drugs"
    - course_name: "Philosophy"
      department: "Arts"
      description: "Study of fundamental questions about knowledge, existence, and values"
    - course_name: "Physics"
      department: "Science"
      description: "Study of matter, energy, and the interactions between them"
    - course_name: "Psychology"
      department: "Health"
      description: "Study of mind and behavior"
    - course_name: "Public Health"
      department: "Health"
      description: "Prevention of disease and promotion of health"
    - course_name: "Software Engineering"
      department: "Engineering"
      description: "Applying engineering principles to software development"