version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: uni_hub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://uni_hub_user:password123@db:5432/uni_hub_db
      POSTGRES_DB: uni_hub_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      SECRET_KEY: secret-key

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres_data:
  local_pgdata:
  pgadmin-data:
