# Generated by Django 5.1.7 on 2025-03-19 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='user',
            new_name='username',
        ),
    ]
