# Generated by Django 5.1.7 on 2025-03-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_user_usersettings_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="username",
            new_name="user",
        ),
    ]
