# Generated by Django 5.1.6 on 2025-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='default_type', max_length=50),
        ),
    ]
