# Generated by Django 5.1.7 on 2025-03-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_interact',
            field=models.BooleanField(default=False),
        ),
    ]
