# Generated by Django 5.1.6 on 2025-02-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='posts.post'),
        ),
    ]
