# Generated by Django 5.1.6 on 2025-02-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_interaction_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ref_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='posts.post'),
        ),
    ]
